### ISSUE TITLE
Mission control - switching desktops not possible.

### ISSUE THREAD

**Issue by vpejcoch** [tanin47/noo#2] opened 2021-02-27 15:05 UTC
Hi, it seems there is something preventing Noo Mouse from controlling Mission Control. Switching desktop spaces in particular (ctrl+left or right arrow). If I map it to some other shortcuts (pg down for example), the mouse button works just fine. If I press ctrl+left or right on my keyboard, it also works. I use Mac OS 10.15.7

**Comment by dcartergig** [comment] 2022-05-09 15:26
I have the same problem. It's like CTRL is not pressed, it registers the arrow keys and will move a cursor.

**Comment by vpejcoch** [comment] 2022-05-09 15:32
Hi, I have been using Karabiner elements, and it works perfectly - https://karabiner-elements.pqrs.org/

a modification is downloadable here - https://ke-complex-modifications.pqrs.org/#mouse_buttons_4_5_desktop_switch

**Comment by tanin47** [comment] 2024-04-22 00:20
I apologize about the inconvenience. There seems to be something special with the button ctrl + arrows. I will need to take a look.

**Comment by tanin47** [comment] 2024-04-22 01:28
I've found the root cause. We are using `postToPid` which sends the keys to a specific application. What we should have used instead is `post(tap:)`, which sends the keys to the window server itself. 

I've tested it, and it works. I'll publish the version 3.1 that solves this issue.

**Comment by tanin47** [comment] 2024-04-22 07:41
This has been fixed and released in the version 3.1.

You can download it from here: https://apps.apple.com/us/app/noo-mouse/id1514904040

**Closed as completed by tanin47** 2024-04-22 07:41 UTC
